apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-configmap
data:
  config.custom.toml: |
{{ .Values.config | indent 4 }}
  genesis.custom.json: |
{{ .Values.genesis | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-env-configmap
data:
  {{- toYaml .Values.env | nindent 2 }}

{{- if .Values.syncCheck.enabled }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-sync-check-env-configmap
data:
  {{- toYaml .Values.syncCheck.env | nindent 2 }}

{{- end }}